Repository PrivaNoteTeam/PrivaNote, pull requests merged in 2021-10, with the labels that each got.

#76 Create, Open Notebook and Menu
  client/package-lock.json
  client/package.json
  client/src/assets/icons/close.svg
  client/src/components/BrowseInputField.tsx
  client/src/components/CreateNotebookModal.tsx
  client/src/components/Modal.tsx
  client/src/components/TextField.tsx
  client/src/custom.d.ts
  client/src/electron.ts
  client/src/electron/applicationMenu.ts
  client/src/electron/handlers/selectDirectory.ts
  client/src/index.tsx
  client/src/styles.css
  client/webpack.config.js
Labels: feature

#83 Fix #81
  client/src/components/CreateNotebookModal.tsx
Labels: bug

#89 Save Notes
  client/package-lock.json
  client/package.json
  client/src/components/editorPanel/Editor.tsx
  client/src/components/editorPanel/editor/Breadcrumb.tsx
  client/src/electron/applicationMenu.ts
  client/src/utils/saveFile.ts
Labels: feature

#90 Notebook Configurations
  client/src/components/CreateNotebookModal.tsx
  client/src/electron/applicationMenu.ts
  client/src/index.tsx
  client/src/types.d.ts
  client/src/utils/createNotebook.ts
  client/src/utils/defaultConfig.ts
  client/src/utils/getConfig.ts
Labels: feature

#94 Toggle File Explorer
  client/src/components/EditorPanel.tsx
  client/src/electron/applicationMenu.ts
Labels: feature

#96 File Explorer Selection
  client/src/components/editorPanel/FileExplorer.tsx
  client/src/components/editorPanel/fileExplorer/Directory.tsx
  client/src/components/editorPanel/fileExplorer/Note.tsx
  client/src/utils/getParentDirectory.ts
Labels: feature

#97 Breadcrumb
  client/src/components/editorPanel/Editor.tsx
  client/src/components/editorPanel/editor/Breadcrumb.tsx
  client/src/utils/useRelativePath.ts
Labels: feature

#99 Breadcrumb Navigation
  client/src/components/EditorPanel.tsx
  client/src/components/editorPanel/Editor.tsx
  client/src/components/editorPanel/FileExplorer.tsx
  client/src/components/editorPanel/editor/Breadcrumb.tsx
  client/src/utils/isFile.ts
Labels: feature, story

#103 Fix #100
  client/src/components/EditorPanel.tsx
Labels: bug

#102 Fix 101
  client/src/components/EditorPanel.tsx
  client/src/index.tsx
Labels: bug

#104 Fix #101 when creating new notebook
  client/src/components/CreateNotebookModal.tsx
  client/src/index.tsx
Labels: bug
